import './globals.css'
import { Poppins } from 'next/font/google'
import Navbar from './components/Navbar'


const poppins = Poppins({
  subsets: ['latin'],
  weight: ["200", "400", "600", "800"],
  variable: "--font-poppins",

})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={`${poppins.variable} font-poppins`}>
      <body className='bg-gray-800 text-white'>
        <Navbar/>
        {children}
        </body>
    </html>
  )
}
